### ISSUE TITLE
Comentarios de los wireframes

### ISSUE THREAD

**Issue by mikeguzman** [una-eif506-18G01/project-1-website-searching-jobs-bravo#1]
Cambios
- [x] No veo un menú principal claro
- [x] Hace falta la página de contáctenos
- [x] Solo veo 2 usuarios asignados al grupo de bravo en github
- [x] Veo 4 UX y mínimo necesito 5 UX
- [x] La opción del mapa esta interesante pero dice "podría" cuando debe de tenerlo si lo ponen en el wireframe

**Comment by Raznagul** [comment]
Elementos mencionados fueron tomados en cuenta en el proyecto
